spring:
  application:
    name: safechat-core

  datasource:
    url: jdbc:mysql://root:seYVBPoyvjJNXbAnCJcryJlTVtmoAEWQ@ballast.proxy.rlwy.net:55443/railway
    username: root
    password: seYVBPoyvjJNXbAnCJcryJlTVtmoAEWQ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  expiration: 3600
logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8084
  servlet:
    context-path: /trackchat
fastapi:
  base-url: http://localhost:8000