spring:
  application:
    name: safechat-core

  datasource:
    url: jdbc:postgresql://localhost:5433/phishingApp
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: secretsecretsecretsecretsecretsecretsecretsecret
  expiration: 3600
logging:
  level:
    org.springframework.web: DEBUG
server:
  port: 8084
  servlet:
    context-path: /trackchat
fastapi:
  base-url: http://localhost:8000